package org.seckill.po;

import java.io.Serializable;
import java.util.Date;

public class MiniappShopSeckillPo implements Serializable {
    /**
     * <pre>
     * 商品库存ID
     * 表字段 : seckill.seckill_id
     * </pre>
     */
    private Long seckillId;

    /**
     * <pre>
     * 商品名称
     * 表字段 : seckill.name
     * </pre>
     */
    private String name;

    /**
     * <pre>
     * 库存数量
     * 表字段 : seckill.number
     * </pre>
     */
    private Integer number;

    /**
     * <pre>
     * 秒杀开始时间
     * 表字段 : seckill.start_time
     * </pre>
     */
    private Date startTime;

    /**
     * <pre>
     * 秒杀结束时间
     * 表字段 : seckill.end_time
     * </pre>
     */
    private Date endTime;

    /**
     * <pre>
     * 创建时间
     * 表字段 : seckill.create_time
     * </pre>
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seckill
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public MiniappShopSeckillPo(Long seckillId, String name, Integer number, Date startTime, Date endTime, Date createTime) {
        this.seckillId = seckillId;
        this.name = name;
        this.number = number;
        this.startTime = startTime;
        this.endTime = endTime;
        this.createTime = createTime;
    }

    /**
     *
     */
    public MiniappShopSeckillPo() {
        super();
    }

    /**
     * <pre>
     * 获取：商品库存ID
     * 表字段：seckill.seckill_id
     * </pre>
     *
     * @return seckill.seckill_id：商品库存ID
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * <pre>
     * 设置：商品库存ID
     * 表字段：seckill.seckill_id
     * </pre>
     *
     * @param seckillId
     *            seckill.seckill_id：商品库存ID
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * <pre>
     * 获取：商品名称
     * 表字段：seckill.name
     * </pre>
     *
     * @return seckill.name：商品名称
     */
    public String getName() {
        return name;
    }

    /**
     * <pre>
     * 设置：商品名称
     * 表字段：seckill.name
     * </pre>
     *
     * @param name
     *            seckill.name：商品名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * <pre>
     * 获取：库存数量
     * 表字段：seckill.number
     * </pre>
     *
     * @return seckill.number：库存数量
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * <pre>
     * 设置：库存数量
     * 表字段：seckill.number
     * </pre>
     *
     * @param number
     *            seckill.number：库存数量
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * <pre>
     * 获取：秒杀开始时间
     * 表字段：seckill.start_time
     * </pre>
     *
     * @return seckill.start_time：秒杀开始时间
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * <pre>
     * 设置：秒杀开始时间
     * 表字段：seckill.start_time
     * </pre>
     *
     * @param startTime
     *            seckill.start_time：秒杀开始时间
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * <pre>
     * 获取：秒杀结束时间
     * 表字段：seckill.end_time
     * </pre>
     *
     * @return seckill.end_time：秒杀结束时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * <pre>
     * 设置：秒杀结束时间
     * 表字段：seckill.end_time
     * </pre>
     *
     * @param endTime
     *            seckill.end_time：秒杀结束时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * <pre>
     * 获取：创建时间
     * 表字段：seckill.create_time
     * </pre>
     *
     * @return seckill.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * <pre>
     * 设置：创建时间
     * 表字段：seckill.create_time
     * </pre>
     *
     * @param createTime
     *            seckill.create_time：创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seckillId=").append(seckillId);
        sb.append(", name=").append(name);
        sb.append(", number=").append(number);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}